using Domain.Enums;

namespace Application.StoragePorts;

// Upload parameters passed from PictureService to the storage adapter. PictureId is generated by
// the caller (before the Picture row is inserted) so the blob name and the eventual row can share
// the same identifier without a round trip back from storage.
public sealed record NewImage(
    PictureOwnerType OwnerType,
    int OwnerId,
    Guid PictureId,
    Stream Content,
    string ContentType,
    string FileExtension);

public sealed record StoredImage(string BlobName, long SizeBytes);

// Port for image-blob persistence (implemented by Infrastructure/Storage/AzureBlobImageStorage.cs),
// isolating Application from the concrete Azure Blob Storage SDK. SQL (the Picture entity) stores
// only the BlobName; read URLs are minted on demand via GetReadUrl so the storage account/SAS key
// can rotate freely without touching persisted data.
public interface IImageStorage
{
    Task<StoredImage> UploadAsync(NewImage upload, CancellationToken cancellationToken = default);

    Uri GetReadUrl(string blobName, TimeSpan? ttl = null);

    Task DeleteAsync(string blobName, CancellationToken cancellationToken = default);

    // Clears every blob in the container. Used by the demo scheduled-reset feature so orphaned
    // images don't accumulate between resets (see ItemCatalogueAPI/ScheduledReset).
    Task DeleteAllAsync(CancellationToken cancellationToken = default);
}
