CREATE TABLE [Person] (
    [Id] INT NOT NULL IDENTITY(1, 1) CONSTRAINT [PK_Person] PRIMARY KEY,
    [Name] NVARCHAR(100) NOT NULL,
    [CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    [LastModifiedDate] DATETIME2 NULL,
    [RowVersion] ROWVERSION NOT NULL
);