import type { CatalogueData } from './types';

// Mirror of the SSDT post-deployment seed scripts, used when the API is unreachable
// so the experience still works as a standalone demo.
export const FALLBACK_DATA: CatalogueData = {
  live: false,
  rooms: [
    { id: 1, name: 'Bedroom', description: 'Main bedroom' },
    { id: 2, name: 'Living Room', description: 'Main living area' },
    { id: 3, name: 'Kitchen', description: 'Kitchen' },
    { id: 4, name: 'Office', description: 'Home office' },
    { id: 5, name: 'Garage', description: 'Garage' },
    { id: 6, name: 'Storage', description: 'Storage room' },
    { id: 7, name: 'Basement', description: 'Basement' },
    { id: 8, name: 'Attic', description: 'Attic' },
    { id: 9, name: 'Bathroom', description: 'Bathroom' },
    { id: 10, name: 'Dining Room', description: 'Dining room' },
    { id: 11, name: 'Glove box', description: 'Glove box of the car' },
    { id: 12, name: 'Trunk', description: 'Trunk of the car' },
  ],
  locations: [
    { id: 1, name: 'Apartment', description: 'My Apartment', roomId: 1 },
    { id: 2, name: 'Grandmas', description: 'Grandmas house', roomId: 2 },
    { id: 3, name: 'House', description: 'My house', roomId: 3 },
    { id: 4, name: 'Storage Unit', description: '#223', roomId: 6 },
    { id: 5, name: 'Car', description: 'Subaru Forester', roomId: 11 },
  ],
  items: [
    {
      id: 1,
      name: 'Laptop',
      description: 'High-performance laptop with 16GB RAM',
      itemTypes: [0],
      price: 1299.99,
      isStored: true,
      isDeleted: false,
      reasonForDeletion: null,
      locationId: 1,
      ownerId: 1,
      createdDate: '2026-01-15T10:00:00Z',
      lastModifiedDate: null,
    },
    {
      id: 2,
      name: 'Wireless Mouse',
      description: 'Ergonomic wireless mouse with USB receiver',
      itemTypes: [0],
      price: 29.99,
      isStored: true,
      isDeleted: false,
      reasonForDeletion: null,
      locationId: 1,
      ownerId: 1,
      createdDate: '2026-01-15T10:05:00Z',
      lastModifiedDate: null,
    },
    {
      id: 3,
      name: 'USB-C Cable',
      description: '2-meter USB-C charging cable',
      itemTypes: [0],
      price: 12.99,
      isStored: true,
      isDeleted: false,
      reasonForDeletion: null,
      locationId: 2,
      ownerId: 2,
      createdDate: '2026-01-16T09:00:00Z',
      lastModifiedDate: null,
    },
    {
      id: 4,
      name: 'Monitor Stand',
      description: 'Adjustable monitor stand for dual displays',
      itemTypes: [0],
      price: 49.99,
      isStored: true,
      isDeleted: false,
      reasonForDeletion: null,
      locationId: 3,
      ownerId: 3,
      createdDate: '2026-01-17T14:30:00Z',
      lastModifiedDate: null,
    },
    {
      id: 5,
      name: 'Mechanical Keyboard',
      description: 'RGB mechanical keyboard with Cherry MX switches',
      itemTypes: [0],
      price: 149.99,
      isStored: true,
      isDeleted: false,
      reasonForDeletion: null,
      locationId: 4,
      ownerId: 4,
      createdDate: '2026-01-18T08:45:00Z',
      lastModifiedDate: null,
    },
  ],
  persons: [
    { id: 1, name: 'Bill' },
    { id: 2, name: 'Jen' },
    { id: 3, name: 'Oscar' },
    { id: 4, name: 'Bowie' },
  ],
};
